# Generated by Django 2.2.7 on 2021-04-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20210413_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FilePathField(path='/home/lucasstonedrake/rp_portfolio/projects/static/img'),
        ),
    ]
