# Generated by Django 2.2.7 on 2021-04-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20210414_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FilePathField(path='/home/lucasstonedrake/rp_portfolio/static/img'),
        ),
    ]
