# Generated by Django 2.2.7 on 2021-04-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20210414_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FilePathField(path='rp_portfolio/static/img'),
        ),
    ]
