# Generated by Django 3.1.7 on 2021-07-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_auto_20210601_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.SmallIntegerField(default=5),
            preserve_default=False,
        ),
    ]
