# Generated by Django 3.1.7 on 2021-07-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_project_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='order',
            field=models.SmallIntegerField(null=True),
        ),
    ]
